# Use lightweight Python base
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy app
COPY app.py .

# Expose port
EXPOSE 80

# Run app
CMD ["python", "app.py"]
